apiVersion: v2
appVersion: "2.0"
description: Helm chart for the HMCTS bar api
name: bar-api
home: https://github.com/hmcts/bar-app
version: 0.2.24
maintainers:
  - name: HMCTS Bar Dev Team
    email: bar@hmcts.net
dependencies:
  - name: java
    version: 5.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
